zookeeper:
  url: localhost:2181
  max-retries: 3
  base-sleep-time-ms: 1000
server:
  port: 9923

im:
  host: 127.0.0.1
  port: 9916


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
